<<<<<<< HEAD
distribution: LO_thrust
order_to_match: 1
name: test
=======
distribution: thrust
order_to_match: 1
name: test2d
>>>>>>> 5281c87249953e4c723d0ff56f3b1af632bea21f
mstar: 1

init_random: true
init_at_answer: false
init_close_to_answer: false
learn_theta: true

ratio_loss: false
use_logbins: false
n_bins: 100
t_min: 0
<<<<<<< HEAD
t_max: 10


epochs: 20000
batch_size: 512
lr: 0.01
seed: 42
m: 3
n: 3
=======
t_max: 7


epochs: 10000
batch_size: 249
lr: 0.01
seed: 42
m: 2
n: 2
>>>>>>> 5281c87249953e4c723d0ff56f3b1af632bea21f

