distribution: thrust
order_to_match: 1
name: test

init_random: true
init_at_answer: false
init_close_to_answer: false
learn_theta: true

ratio_loss: false
use_logbins: false
n_bins: 50
t_min: 0
t_max: 8

epochs: 10000
batch_size: 128
lr: 0.001
seed: 42
m: 2
n: 9

