distribution: thrust
run_toy: false
order_to_match: 2
name: 3d
mstar: 1

init_random: true
init_at_answer: false
init_close_to_answer: false
learn_theta: true

ratio_loss: false
weighted_mse_loss: false
use_logbins: false
n_bins: 100
t_min: 0
t_max: 10


epochs: 20000
batch_size: 345
lr: 0.01
seed: 42
m: 2
n: 10


device: "cuda"
