distribution: thrust
order_to_match: 1
name: test2d
mstar: 1

init_random: true
init_at_answer: false
init_close_to_answer: false
learn_theta: true

ratio_loss: false
use_logbins: false
n_bins: 100
t_min: 0
t_max: 7


epochs: 10000
batch_size: 249
lr: 0.01
seed: 42
m: 2
n: 2

